# Schema for the configuration files of the template form module.
template_form.settings:
  type: config_object
  label: 'template form settings'
  mapping:
    example:
      type: string
      label: 'Example'
